apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.screencapture'
version = '1.0.0'

android {
  namespace 'expo.modules.screencapture'
  compileSdk rootProject.ext.compileSdkVersion

  defaultConfig {
    minSdk rootProject.ext.minSdkVersion
  }

  kotlinOptions {
    jvmTarget = '17'
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
