const { withAppBuildGradle } = require('@expo/config-plugins')

/**
 * Resolves the `${MAPS_API_KEY}` placeholder that `app.json` puts in the manifest.
 *
 * `AndroidManifest.xml` is generated by prebuild but tracked in git, so a literal key written there
 * would be committed. Keeping a placeholder in the manifest and substituting at build time leaves
 * the repository clean; the value lives in `~/.gradle/gradle.properties` next to the signing
 * credentials, or in the environment for CI.
 */
// Debug and release are signed by different certificates, and a Maps key is bound to one of them,
// so each build type gets its own. Without this the key had to be swapped by hand before every
// release build.
const debugPlaceholder = `            manifestPlaceholders = [
                MAPS_API_KEY: (project.findProperty('PASTVU_MAPS_API_KEY_DEBUG')
                    ?: System.getenv('GOOGLE_MAPS_API_KEY_DEBUG') ?: '')
            ]
`
const releasePlaceholder = `            manifestPlaceholders = [
                MAPS_API_KEY: (project.findProperty('PASTVU_MAPS_API_KEY')
                    ?: System.getenv('GOOGLE_MAPS_API_KEY') ?: '')
            ]
`

const withMapsKeyPlaceholder = config =>
  withAppBuildGradle(config, config => {
    const contents = config.modResults.contents
    if (contents.includes('MAPS_API_KEY:')) {
      return config
    }
    config.modResults.contents = contents
      .replace(/(buildTypes \{\n\s*debug \{\n)/, `$1${debugPlaceholder}`)
      .replace(/(\n        release \{\n)/, `$1${releasePlaceholder}`)
    return config
  })

module.exports = withMapsKeyPlaceholder
